name: Captive-Portal-Image-Gallery
services:
  simple-image-gallery:
    image: ghcr.io/louuke/simple-image-gallery:latest
    container_name: simple-image-gallery
    ports:
      - "192.168.137.1:5000:80/tcp"
    volumes:
      - ".:/images"
    environment:
      GALLERY_DIRECTORY: "/images"
      GALLERY_HEADER: "my images"
      GALLERY_IMAGE_DATE_FORMAT: "%m/%d/%Y %I:%M %p"
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "192.168.137.1:80:80/tcp"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
  dnschef:
    image: ghcr.io/louuke/dnschef-ng:latest
    container_name: dnschef-ng
    ports:
      - "192.168.137.1:53:53/udp"
    expose:
      - 80
    volumes:
      - ./dnschef.toml:/etc/dnschef.toml
    environment:
      - INTERFACE=0.0.0.0
      - PORT=53
      - TCP=false
      - IPV6=false
      - CONFIGFILE=/etc/dnschef.toml